name: "tagged-release"
on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo ::set-output name=release-file::backup-rsync-${GITHUB_REF#refs/*/}.tar.gz
      - name: Create release archive
        run: |
          cd ${{ github.workspace }}
          find . \( -path ./lib -prune -o -name '*.sh' -print \) -o  -name 'backup-rsync' -print -exec chmod 700 {} +
          find . -type d -exec chmod 700 {} +
          chmod 600 .env.example
          tar -vczf /tmp/${{ steps.vars.outputs.release-file }} --owner=0 --group=0 --no-same-owner --exclude='.git*' ../backup-rsync
          mv /tmp/${{ steps.vars.outputs.release-file }} ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true,
          files: |
            ${{ steps.vars.outputs.release-file }}
